### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by rjeczalik** [streadway/amqp#160]
The following program:

``` go
~ $ cat a.go
package main

import (
        "log"
        "os"

        "github.com/streadway/amqp"
)

func main() {
        conn, err := amqp.Dial(os.Getenv("RABBITMQ"))
        if err != nil {
                log.Fatal(err)
        }
        c := make(chan *amqp.Error, 2)
        ch, err := conn.Channel()
        if err != nil {
                log.Fatal(err)
        }
        conn.NotifyClose(c)
        ch.NotifyClose(c)
        if err = conn.Close(); err != nil {
                log.Fatal()
        }
        for err := range c {
                log.Println("notified:", err)
        }
}
```

Panics with:

```
~ $ go run a.go 
panic: close of closed channel

goroutine 1 [running]:
github.com/streadway/amqp.(*Connection).shutdown.func1()
        /Users/rjeczalik/src/github.com/streadway/amqp/connection.go:360 +0x235
sync.(*Once).Do(0xc82009e000, 0xc820057d90)
        /Users/rjeczalik/go/src/sync/once.go:44 +0xe4
github.com/streadway/amqp.(*Connection).shutdown(0xc82009e000, 0x0)
        /Users/rjeczalik/src/github.com/streadway/amqp/connection.go:370 +0x49
github.com/streadway/amqp.(*Connection).Close(0xc82009e000, 0x0, 0x0)
        /Users/rjeczalik/src/github.com/streadway/amqp/connection.go:303 +0x1cb
main.main()
        /Volumes/copper.io/src/github.com/pandastream/live/bug.go:22 +0x2a2
```

**Comment by ilgooz** [comment]
You must initialize different go channels for each use. Once a go channel closed by a Connection or Channel in your case, it'll not be able to writable/closable again with another one which is a natural behavior of Go.

**Comment by michaelklishin** [comment]
Looks like this is an answered question.
