### ISSUE TITLE
ImportError: cannot import name spec

### ISSUE THREAD

**Issue by Hoohaha** [streadway/amqp#271]
Hi sir,

```
amqp Version: 2.1.4
djang version: 1.11.1
celery version: 4.0.2
apache version: 2.4
```

I want to use celery in my django project. The project is served by apache-server.
When the server is started. There are an error display:

```
[Wed May 24 04:03:26.076766 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534] mod_wsgi (pid=10092): Target WSGI script '/opt/lampp/htdocs/dpcm/dpcm1/wsgi.py' cannot be loaded as Python module.
[Wed May 24 04:03:26.076836 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534] mod_wsgi (pid=10092): Exception occurred processing WSGI script '/opt/lampp/htdocs/dpcm/dpcm1/wsgi.py'.
[Wed May 24 04:03:26.076891 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534] Traceback (most recent call last):
[Wed May 24 04:03:26.076936 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm1/wsgi.py", line 18, in <module>
[Wed May 24 04:03:26.077076 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     application = get_wsgi_application()
[Wed May 24 04:03:26.077101 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
[Wed May 24 04:03:26.077187 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     django.setup(set_prefix=False)
[Wed May 24 04:03:26.077210 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
[Wed May 24 04:03:26.077288 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed May 24 04:03:26.077312 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
[Wed May 24 04:03:26.077487 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     self._setup(name)
[Wed May 24 04:03:26.077507 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
[Wed May 24 04:03:26.077545 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     self._wrapped = Settings(settings_module)
[Wed May 24 04:03:26.077562 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
[Wed May 24 04:03:26.077587 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed May 24 04:03:26.077652 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Wed May 24 04:03:26.077791 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     __import__(name)
[Wed May 24 04:03:26.077813 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm1/__init__.py", line 5, in <module>
[Wed May 24 04:03:26.077876 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from .celery import app as celery_app
[Wed May 24 04:03:26.077894 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm1/celery.py", line 3, in <module>
[Wed May 24 04:03:26.077958 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from celery import Celery
[Wed May 24 04:03:26.077977 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/celery/local.py", line 509, in __getattr__
[Wed May 24 04:03:26.078311 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     module = __import__(self._object_origins[name], None, None, [name])
[Wed May 24 04:03:26.078330 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/celery/app/__init__.py", line 5, in <module>
[Wed May 24 04:03:26.078427 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from celery import _state
[Wed May 24 04:03:26.078445 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/celery/_state.py", line 15, in <module>
[Wed May 24 04:03:26.078583 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from celery.utils.threads import LocalStack
[Wed May 24 04:03:26.078601 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/celery/utils/__init__.py", line 10, in <module>
[Wed May 24 04:03:26.078856 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from .nodenames import worker_direct, nodename, nodesplit
[Wed May 24 04:03:26.078880 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/celery/utils/nodenames.py", line 7, in <module>
[Wed May 24 04:03:26.078984 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from kombu.entity import Exchange, Queue
[Wed May 24 04:03:26.079002 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/kombu/entity.py", line 6, in <module>
[Wed May 24 04:03:26.079555 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from .abstract import MaybeChannelBound, Object
[Wed May 24 04:03:26.079576 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/kombu/abstract.py", line 6, in <module>
[Wed May 24 04:03:26.079758 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from .connection import maybe_channel
[Wed May 24 04:03:26.079784 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/kombu/connection.py", line 15, in <module>
[Wed May 24 04:03:26.080421 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from kombu import exceptions
[Wed May 24 04:03:26.080441 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/kombu/exceptions.py", line 6, in <module>
[Wed May 24 04:03:26.080550 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from amqp import ChannelError, ConnectionError, ResourceError
[Wed May 24 04:03:26.080569 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/amqp/__init__.py", line 47, in <module>
[Wed May 24 04:03:26.080747 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from .connection import Connection  # noqa
[Wed May 24 04:03:26.080787 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]   File "/opt/lampp/htdocs/dpcm/dpcm/local/lib/python2.7/site-packages/amqp/connection.py", line 29, in <module>
[Wed May 24 04:03:26.081249 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534]     from . import spec
[Wed May 24 04:03:26.081306 2017] [wsgi:error] [pid 10092] [client 192.168.17.130:48534] ImportError: cannot import name spec
```
amqp/connection.py", line 29:
```python
from . import spec
```
What's the problem?

**Comment by Hoohaha** [comment]
sorry, i made a mistake, this is not python amqp.
