### ISSUE TITLE
"panic: send on closed channel" on amqp confirms

### ISSUE THREAD

**Issue by dimm0** [streadway/amqp#274]
I'm hitting these errors from time to time:

```
panic: send on closed channel

goroutine 19094 [running]:
github.com/streadway/amqp.(*confirms).confirm(0xc420140000, 0x1, 0xc420140001)
        /home/dmishin/go/src/github.com/streadway/amqp/confirms.go:45 +0xac
github.com/streadway/amqp.(*confirms).One(0xc420140000, 0x1, 0x1001)
        /home/dmishin/go/src/github.com/streadway/amqp/confirms.go:66 +0x8c
github.com/streadway/amqp.(*Channel).dispatch(0xc42021e000, 0xe2ec00, 0xc420b42950)
        /home/dmishin/go/src/github.com/streadway/amqp/channel.go:309 +0x88d
github.com/streadway/amqp.(*Channel).recvMethod(0xc42021e000, 0xe2adc0, 0xc42022e500, 0xc42007a3d8, 0x1)
        /home/dmishin/go/src/github.com/streadway/amqp/channel.go:346 +0x34c
github.com/streadway/amqp.(*Connection).dispatchN(0xc4205d0140, 0xe2adc0, 0xc42022e500)
        /home/dmishin/go/src/github.com/streadway/amqp/connection.go:470 +0xd0
github.com/streadway/amqp.(*Connection).demux(0xc4205d0140, 0xe2adc0, 0xc42022e500)
        /home/dmishin/go/src/github.com/streadway/amqp/connection.go:429 +0x89
github.com/streadway/amqp.(*Connection).reader(0xc4205d0140, 0x7f9c40ee7200, 0xc42016a008)
        /home/dmishin/go/src/github.com/streadway/amqp/connection.go:521 +0x117
created by github.com/streadway/amqp.Open
        /home/dmishin/go/src/github.com/streadway/amqp/connection.go:228 +0x32d
```

Can't reproduce this in a test case. I'm using the pubsub example in my code. Could somebody help me debug the issue?

**Comment by dimm0** [comment]
I see it happening after a redial, when the connection has been closed. I modified the example to open the channel and exchange for publisher and consumer separately.

The code is here: https://github.com/sdsc/pdm/blob/master/main.go#L124

How can I test this? Should I explicitly close the "NotifyPublish" listener?

**Comment by dimm0** [comment]
I think I fixed it.

This block https://github.com/streadway/amqp/blob/master/_examples/pubsub/pubsub.go#L90-L95 should be inside the sessions loop, since "confirm" channel is being closed when a connection closes.

**Comment by michaelklishin** [comment]
@dimm0 please submit a PR?

**Comment by dimm0** [comment]
Sure
