### ISSUE TITLE
Data race while closing connection after publishing

### ISSUE THREAD

**Issue by pardhasm** [streadway/amqp#428]
I am publishing messages to rabbitMQ at a small rate (30/s). If I close the connection after the message publishes, it is giving me the below error.

```
fatal error: concurrent map read and map write

goroutine 10 [running]:
runtime.throw(0x18e7d4f, 0x21)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:774 +0x72 fp=0xc00005fe28 sp=0xc00005fdf8 pc=0x102fcc2
runtime.mapaccess1(0x17be000, 0xc0000c4690, 0xc00005fe9e, 0x1)
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/map.go:411 +0x269 fp=0xc00005fe70 sp=0xc00005fe28 pc=0x100f889
github.com/streadway/amqp.(*Connection).dispatchN(0xc0002c8000, 0x1a0ac80, 0xc0004c0f60)
        /Users/pardhasaradhi/go/pkg/mod/github.com/streadway/amqp@v0.0.0-20190827072141-edfb9018d271/connection.go:473 +0x8c fp=0xc00005fec0 sp=0xc00005fe70 pc=0x16ed13c
github.com/streadway/amqp.(*Connection).demux(0xc0002c8000, 0x1a0ac80, 0xc0004c0f60)
        /Users/pardhasaradhi/go/pkg/mod/github.com/streadway/amqp@v0.0.0-20190827072141-edfb9018d271/connection.go:436 +0x87 fp=0xc00005fee8 sp=0xc00005fec0 pc=0x16ecc57
github.com/streadway/amqp.(*Connection).reader(0xc0002c8000, 0x2419078, 0xc000010080)
        /Users/pardhasaradhi/go/pkg/mod/github.com/streadway/amqp@v0.0.0-20190827072141-edfb9018d271/connection.go:528 +0xf4 fp=0xc00005ffc8 sp=0xc00005fee8 pc=0x16ed414
runtime.goexit()
        /usr/local/Cellar/go/1.13.1/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00005ffd0 sp=0xc00005ffc8 pc=0x105c891
created by github.com/streadway/amqp.Open
        /Users/pardhasaradhi/go/pkg/mod/github.com/streadway/amqp@v0.0.0-20190827072141-edfb9018d271/connection.go:233 +0x260
```
My code:

```
func Publish(name string, body []byte) {
    channel, err := connection.Channel()
    defer channel.Close() // commenting out this does not cause any errors but too many channels are left.
    err := channel.Publish("", name, false, false, amqp.Publishing{
        DeliveryMode: amqp.Persistent,
        ContentType:  "text/plain",
        Body:         body,
    })
    util.HandlerError(err, "Could not publish message for mq : "+name)
}
```

**Comment by ljluestc** [comment]
```
package main

import (
    "log"
    "os"
    "time"

    "github.com/streadway/amqp"
)

// Connection is a global AMQP connection
var connection *amqp.Connection

// HandlerError logs errors and exits if fatal
func HandlerError(err error, msg string) {
    if err != nil {
        log.Printf("Error: %s - %v", msg, err)
        os.Exit(1)
    }
}

// Publish sends a message to RabbitMQ with publisher confirms
func Publish(name string, body []byte) {
    // Open a channel
    channel, err := connection.Channel()
    if err != nil {
        HandlerError(err, "Failed to open channel")
        return
    }
    defer channel.Close() // Still deferred, but safe with confirms

    // Enable publisher confirms
    err = channel.Confirm(false)
    if err != nil {
        HandlerError(err, "Failed to enable confirms")
        return
    }

    // Publish the message
    err = channel.Publish(
        "",           // Exchange
        name,         // Routing key (queue name)
        false,        // Mandatory
        false,        // Immediate
        amqp.Publishing{
            DeliveryMode: amqp.Persistent,
            ContentType:  "text/plain",
            Body:         body,
        },
    )
    if err != nil {
        HandlerError(err, "Could not publish message for mq: "+name)
        return
    }

    // Wait for confirmation
    confirmChan := channel.NotifyPublish(make(chan amqp.Confirmation, 1))
    confirmed := <-confirmChan
    if !confirmed.Ack {
        log.Printf("Message to %s was not acknowledged", name)
        return
    }

    log.Printf("Message to %s published and confirmed", name)
}

func main() {
    // Connect to RabbitMQ
    var err error
    connection, err = amqp.Dial("amqp://guest:guest@localhost:5672/")
    if err != nil {
        HandlerError(err, "Failed to connect to RabbitMQ")
        return
    }
    defer connection.Close()

    // Declare a durable queue
    channel, err := connection.Channel()
    if err != nil {
        HandlerError(err, "Failed to open channel for queue declaration")
        return
    }
    _, err = channel.QueueDeclare(
        "test_queue", // Queue name
        true,         // Durable
        false,        // Auto-delete
        false,        // Exclusive
        false,        // No-wait
        nil,          // Arguments
    )
    if err != nil {
        HandlerError(err, "Failed to declare queue")
        return
    }
    channel.Close()

    // Simulate publishing 30 messages per second for 5 seconds
    ticker := time.NewTicker(33 * time.Millisecond) // ~30 messages/second
    defer ticker.Stop()

    for i := 0; i < 150; i++ { // 30 msg/s * 5s = 150 messages
        <-ticker.C
        go Publish("test_queue", []byte(fmt.Sprintf("Message %d", i)))
    }

    // Allow time for all messages to process
    time.Sleep(6 * time.Second)
    log.Println("Finished publishing messages")
}
```
